logging_level: "DEBUG" # TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL

defaults:
  - analysis/experiment: metadata
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_ # keep this to the end of defaults to have config.yaml override values set in other yamls

hydra:
  output_subdir: null
  run:
    dir: .

dataset:
  raw_dir: '/home/sebalzer/Documents/Projects/Myo_Flamber/0_raw/'
  out_dir: '/home/sebalzer/Documents/Projects/Myo_Flamber/'
  mdata_src: '/home/sebalzer/Documents/Projects/Myo_Flamber/Final_Regional_Database.xlsx'
  save_intermediate: False # save intermediate steps
  save_final: True # save the final pre-processed tables (only relevant if save_intermediate is False)
  dims: ["2d"] # ['2d', '3d'], which data to include in the pre-processing/analysis
  strict: False # strict behaviour for cleaner and checker, strict=False leads to fewer patients dropped and possible data imputation later

merge:
  peak_values: True # reduce data to peak values (i.e. lose time component)
  keep_thresh: 0.5  # keep only features/patients with at least keep_thresh data
  overwrite: True # overwrite merged data

analysis:
  experiment:
    name: "flamber_all_features" # experiment name (i.e. file name in which to store merged data)
    axes: ["long_axis", "short_axis"] # ['long_axis', 'short_axis']
    metrics: ["strain"] # ['strain', 'strain_rate', 'displacement', 'velocity']
    segments: ["roi"] # ['global', 'aha', 'roi']
    orientations: ["radial", "circumf", "longit"] # ['radial', 'circumf', 'longit']
    target_label: "mace" # which column to use as label for exploration, feature reduction and analysis